### ISSUE TITLE
Build broken: controller-runtime 0.22.4 incompatible with addon-framework v1.0.1

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/ocm-status-addon#160]
## Summary

Main branch is broken after merging PR #131 which bumped `controller-runtime` from 0.20.4 to 0.22.4.

## Error

```
open-cluster-management.io/addon-framework@v1.0.1/pkg/cmd/factory/factory.go:135:46: undefined: utilversion.NewEffectiveVersion
```

## Root Cause

`addon-framework v1.0.1` uses `utilversion.NewEffectiveVersion` which no longer exists in `controller-runtime v0.22.4`.

## Fix Options

1. **Revert PR #131** to restore build
2. **Update addon-framework** to a version compatible with controller-runtime 0.22.4
3. **Downgrade controller-runtime** to a version compatible with addon-framework v1.0.1

## Related

- Breaking commit: 7daf840
- Failed workflow: https://github.com/kubestellar/ocm-status-addon/actions/runs/20969918465

---
🤖 Auto-generated by Claude Code
